version: 2.1

jobs:
  docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: docker build . -t darakeon/mebrak -f docker/mebrak.dockerfile
      - run:
          name: Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Push
          command: docker push darakeon/mebrak

workflows:
  deploy:
    jobs:
      - docker:
          filters:
            branches:
              only: main
