version: 2.1

jobs:
  trufflehog:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: install trufflehog
          command: apk add --no-cache git && pip install gitdb2==3.0.0 trufflehog
      - run:
          name: run trufflehog
          command: trufflehog --exclude_paths trufflehog/exclude-patterns.txt --allow trufflehog/allow.json .

  docker:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build
          command: docker build . -t darakeon/mebrak -f docker/mebrak.dockerfile
      - run:
          name: Push
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
              docker push darakeon/mebrak
            else
              echo 'no main, no push'
            fi

  static:
    docker:
      - image: python
      - image: darakeon/mebrak
    steps:
      - checkout
      - run:
          name: Dependencies
          command: pip install requests boto3
      - run:
          name: Crowler
          path: static
          command: |
            python crowler.py
            if [ "$(git diff)" != "" ]; then
              exit 1
            fi


workflows:
  deploy:
    jobs:
      - trufflehog
      - docker:
          requires:
            - trufflehog
      - static:
          requires:
            - docker
