version: 2.1

jobs:
  trufflehog:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: install trufflehog
          command: apk add --no-cache git && pip install gitdb2==3.0.0 trufflehog
      - run:
          name: run trufflehog
          command: trufflehog --exclude_paths trufflehog/exclude-patterns.txt --allow trufflehog/allow.json .

  docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: docker build . -t darakeon/mebrak -f docker/mebrak.dockerfile
      - run:
          name: Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Push
          command: docker push darakeon/mebrak

workflows:
  deploy:
    jobs:
      - trufflehog
      - docker:
          filters:
            branches:
              only: main
          requires:
            - trufflehog
